---
- name: apply common configuration to all hosts
  hosts: common
  become: yes
  vars: 
    dev_users: "{{ hostvars[groups['common'][0]]['dev_users'] }}"
    environment_name: "{{ hostvars[groups['environment'][0]]['env_name'] }}"

  roles:
    - user-accounts