---
- name: apply common configuration to all hosts
  hosts: jenkins
  become: yes
  vars:
     version_number: '{{helloworld_version}}'
  roles:
    - { role: api/helloworld, app_version : '{{version_number}}' }