---
- name: apply common configuration to all hosts
  hosts: api
  become: yes
  vars:
     version_number: '{{helloworld_version}}'
  roles:
    - { role: docker}
    - { role: api/helloworld, app_version : '{{version_number}}' }