---
- name: Update ssh configuration
  hosts: jenkins-slave
  gather_facts: true
  become: true
  tasks:
    - name: install java 
      yum:
         name: java-1.8.0-openjdk
         state: present
    