---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  
- name: Install git
  yum: 
    name: git 
    state: present

- name: install Apache
  yum:
    name: httpd
    state: present